[package]
name = "autostart-installer"
version.workspace = true
edition = "2024"
authors.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
shared.workspace = true
winreg = "0.55.0"

[build-dependencies]
winres.workspace = true

[lints]
workspace = true
