[package]
name = "autostart-installer"
version = "0.3.2"
edition = "2024"

[dependencies]
shared.workspace = true
winreg = "0.55.0"

[build-dependencies]
winres.workspace = true

[lints]
workspace = true
